### ISSUE TITLE
Slow Download

### ISSUE THREAD

**Issue by camjac251** [Neztore/save-server#1]
I'm trying this script with a large 5GB file and it uploaded really fast in ShareX. Compared to another upload script in PHP, this one is processed by the server instantly which is very nice. Although I am having some trouble with downloading speeds. On the PHP app, I get 30MB/s but here it seems locked at 1.2MB/s. Is there a bottleneck somewhere?

**Comment by Neztore** [comment]
Hi, if there is a bottleneck anywhere this is related to the NodeJS architecture rather than the server implementation itself.
File handling is done through ExpressJS's Response.SendFile method, which as far I'm aware makes use of the built in features of Streams to send the response.

The server isn't really intended for such large files, as generally such large files would be dealt with an application that is not single threaded.
If you can find anything regarding NodeJS/Express download sendFile performance please do link to me but I don't think this is something I can fix at an application level.

**Comment by camjac251** [comment]
Thank you for the fast reply. If it's a limitation then that's too bad. I'll definitely do some research and get back to you. I'm currently using a PHP implementation and it's not without issues. This script is almost instant from upload to the server seeing it, vs PHP having to copy the file before it can be read

**Comment by Neztore** [comment]
Could it be an issue with your server, or if you are using a reverse proxy an issue there perhaps? I know I've had issues in the past with Nginx and it's behaviour with files.

**Comment by camjac251** [comment]
I'm testing it directly from the node server. Nothing inbetween.
