### ISSUE TITLE
(413) Payload Too Large.

### ISSUE THREAD

**Issue by jacobvdl** [Neztore/save-server#28]
**Describe the bug**
When I try uploading a file around 1MB or more it does not let me, some screenshots also give this error.

**To Reproduce**
1. Get a 1MB file or bigger.
2. Upload the file and it will give you the error.

**Expected behavior**
The file should upload normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/46667568/133008826-bd98b71d-ed1c-4c1b-8463-6ab007961963.png)

**Additional context**
Latest ShareX version.

**Comment by Neztore** [comment]
This is a common issue, and is usually not due to Save-Server itself. The default limit within save-server is around 10mb

Nginx, by default, applies a low payload limit. [Follow these steps](https://www.tecmint.com/limit-file-upload-size-in-nginx/) to fix this - most proxy softwares, I imagine, apply a similar restriction by default.

**Comment by jacobvdl** [comment]
Hey, I have tried that and it has worked. I have also found how to change the default save-server limit. Thanks!
